export enum Role {
    SUPER_ADMIN = 'SUPER_ADMIN',
    CONTADOR = 'CONTADOR',
    CLIENTE = 'CLIENTE',
    AUDITOR = 'AUDITOR',
}

export const PERMISSIONS = {
    [Role.SUPER_ADMIN]: ['*'],
    [Role.CONTADOR]: [
        'company:read',
        'company:update',
        'transaction:create',
        'transaction:read',
        'transaction:update',
        'transaction:delete',
        'client:create',
        'client:read',
        'client:update',
        'client:delete',
        'category:create',
        'category:read',
        'category:update',
        'category:delete',
        'payroll:create',
        'payroll:read',
        'payroll:update',
        'payroll:delete',
        'loan:create',
        'loan:read',
        'loan:update',
        'loan:delete',
        'provision:create',
        'provision:read',
        'provision:update',
        'provision:delete',
        'fixed-asset:create',
        'fixed-asset:read',
        'fixed-asset:update',
        'fixed-asset:delete',
        'legal-book:create',
        'legal-book:read',
        'report:read',
        'report:generate',
        'report:export',
        'financial:read',
        'tax:read',
        'audit_log:read',
    ],
    [Role.CLIENTE]: [
        // Lectura de todo
        'company:read',
        'dashboard:read',
        'transaction:read',
        'transaction:create',   // → siempre queda en PENDING_APPROVAL
        'client:read',
        'category:read',
        'payroll:read',
        'loan:read',
        'provision:read',
        'fixed-asset:read',
        'legal-book:read',
        'report:read',
        'report:generate',
        'report:export',
        'financial:read',
        'tax:read',
        // Sin permisos de edición/borrado
    ],
    [Role.AUDITOR]: [
        'company:read',
        'transaction:read',
        'client:read',
        'client:read',
        'category:read',
        'payroll:read',
        'loan:read',
        'provision:read',
        'fixed-asset:read',
        'legal-book:read',
        'report:read',
        'financial:read',
        'tax:read',
        'audit_log:read',
    ],
};

export function hasPermission(role: Role, permission: string): boolean {
    if (role === Role.SUPER_ADMIN) return true;
    const rolePermissions = PERMISSIONS[role] || [];
    return rolePermissions.includes(permission);
}
