import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { getAuthFromRequest } from '@/lib/auth/jwt';
import { SV_DEPRECIATION_RATES } from '@/lib/sv-chart-of-accounts';
import { TaxRuleService } from '@/lib/tax-rules';

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const auth = await getAuthFromRequest(request);
    if (!auth) return NextResponse.json({ error: 'No autenticado' }, { status: 401 });
    const { requirePermission } = await import('@/lib/auth/authorize');
    const permError = requirePermission(auth.role, 'fixed-asset:update');
    if (permError) return permError;

    const { id } = await params;
    const asset = await (prisma.fixedAsset as any).findUnique({
      where: { id },
    });
    if (!asset) return NextResponse.json({ error: 'Activo no encontrado' }, { status: 404 });
    if (asset.status !== 'ACTIVE') {
      return NextResponse.json({ error: 'El activo no está activo' }, { status: 400 });
    }
    if (asset.bookValue <= 0) {
      return NextResponse.json({ error: 'El activo ya está completamente depreciado' }, { status: 400 });
    }

    const body = await request.json().catch(() => ({}));
    const now = new Date();
    const year = body.year ?? now.getFullYear();
    const month = body.month ?? (now.getMonth() + 1);

    // Verificar si ya se depreció este mes (FISCAL)
    const existingFiscal = await (prisma.assetDepreciation as any).findUnique({
      where: {
        assetId_year_month_depreciationType: {
          assetId: id,
          year,
          month,
          depreciationType: 'FISCAL'
        }
      },
    });
    if (existingFiscal) {
      return NextResponse.json(
        { error: `Ya se registró depreciación FISCAL para ${month}/${year}` },
        { status: 409 }
      );
    }

    // ── 1. CÁLCULO FISCAL (Ley ISR) ──────────────────────────────────────────
    const fiscalMonthlyAmount = (asset.purchaseCost - asset.residualValue) / (asset.usefulLifeYears * 12);
    const fiscalAmount = Math.min(fiscalMonthlyAmount, asset.bookValue - asset.residualValue);
    const newFiscalAccumulated = asset.accumulatedDepr + fiscalAmount;
    const newFiscalBookValue = asset.purchaseCost - newFiscalAccumulated;

    // ── 2. CÁLCULO NIIF (Sección 17) ──────────────────────────────────────────
    const niifLife = asset.niifUsefulLifeYears || asset.usefulLifeYears;
    const niifResidual = asset.niifResidualValue ?? asset.residualValue;
    const niifMonthlyAmount = (asset.purchaseCost - niifResidual) / (niifLife * 12);
    
    // Usar niifBookValue si existe, si no purchaseCost (primer mes)
    const currentNiifBookValue = asset.niifBookValue ?? asset.purchaseCost;
    const niifAmount = Math.min(niifMonthlyAmount, currentNiifBookValue - niifResidual);
    const newNiifAccumulated = asset.niifAccumulatedDepr + niifAmount;
    const newNiifBookValue = asset.purchaseCost - newNiifAccumulated;

    // ── 3. DIFERENCIA TEMPORARIA E ISR DIFERIDO ──────────────────────────────
    // Si Depr Fiscal > Depr NIIF = Pasivo Diferido (pagarás más ISR mañana)
    // Si Depr Fiscal < Depr NIIF = Activo Diferido (pagaste más ISR hoy)
    const diffTemporaria = fiscalAmount - niifAmount;
    const isrRate = await TaxRuleService.getRate(asset.companyId, 'ISR_25'); // simplificado
    const isrDiferido = diffTemporaria * isrRate;

    const rateConfig = SV_DEPRECIATION_RATES[asset.accountCode];
    const deprCode = rateConfig?.deprCode ?? `${asset.accountCode}D`;

    // Crear asiento contable: DB 6116 / CR {deprCode}
    let journalEntryId: string | null = null;
    try {
      const companyId = asset.companyId;

      const getOrCreate = async (code: string, name: string, type: string) => {
        const existing = await prisma.account.findUnique({
          where: { companyId_code: { companyId, code } },
        });
        if (existing) return existing.id;
        const created = await prisma.account.create({
          data: { companyId, code, name, type },
        });
        return created.id;
      };

      const [debitId, creditId, deferredTaxId] = await Promise.all([
        getOrCreate('6116', 'Depreciaciones', 'GASTO'),
        getOrCreate(deprCode, `Depreciación Acumulada — ${asset.name}`, 'ACTIVO'),
        isrDiferido > 0 
          ? getOrCreate('2117', 'ISR Diferido por Pagar (Dif. Temporaria)', 'PASIVO')
          : getOrCreate('1109', 'ISR Diferido Activo (Dif. Temporaria)', 'ACTIVO'),
      ]);

      const entry = await prisma.journalEntry.create({
        data: {
          date: new Date(year, month - 1, 1),
          description: `Depreciación NIIF: ${asset.name} (${month}/${year})`,
          companyId,
          metadata: { 
            assetId: id, year, month, autoGenerated: true,
            fiscalAmount, niifAmount, diffTemporaria, isrDiferido
          },
          lines: {
            create: [
              // La contabilidad (NIIF) registra la depreciación técnica
              { accountId: debitId, debit: niifAmount, credit: 0 },
              { accountId: creditId, debit: 0, credit: niifAmount },
              // Registro del ISR Diferido por la diferencia con lo fiscal
              ...(Math.abs(isrDiferido) > 0.01 ? [{
                accountId: deferredTaxId,
                debit: isrDiferido < 0 ? Math.abs(isrDiferido) : 0,
                credit: isrDiferido > 0 ? isrDiferido : 0,
              }] : []),
              // Contrapartida del impuesto diferido (ajuste a la cuenta de gastos por impuesto)
              ...(Math.abs(isrDiferido) > 0.01 ? [{
                accountId: await getOrCreate('6117', 'Impuesto sobre la Renta Diferido', 'GASTO'),
                debit: isrDiferido > 0 ? isrDiferido : 0,
                credit: isrDiferido < 0 ? Math.abs(isrDiferido) : 0,
              }] : []),
            ],
          },
        },
      });
      journalEntryId = entry.id;
    } catch (je) {
      console.warn('Journal entry warning (depreciation):', je);
    }

    // Registrar ambas depreciaciones (FISCAL y NIIF) y actualizar activo
    const results = await prisma.$transaction([
      (prisma.assetDepreciation as any).create({
        data: {
          assetId: id, year, month,
          amount: fiscalAmount,
          accumulatedDepr: newFiscalAccumulated,
          depreciationType: 'FISCAL',
          journalEntryId,
        },
      }),
      (prisma.assetDepreciation as any).create({
        data: {
          assetId: id, year, month,
          amount: niifAmount,
          accumulatedDepr: newNiifAccumulated,
          depreciationType: 'NIIF',
          journalEntryId,
        },
      }),
      (prisma.fixedAsset as any).update({
        where: { id },
        data: {
          accumulatedDepr: newFiscalAccumulated,
          bookValue: newFiscalBookValue,
          niifAccumulatedDepr: newNiifAccumulated,
          niifBookValue: newNiifBookValue,
          status: newNiifBookValue <= niifResidual ? 'FULLY_DEPRECIATED' : 'ACTIVE',
        },
      }),
    ]);

    return NextResponse.json({
      depreciation: results[0], // retornar fiscal por compatibilidad UI
      niifDepreciation: results[1],
      asset: { 
        fiscal: { bookValue: newFiscalBookValue, accumulatedDepr: newFiscalAccumulated },
        niif: { bookValue: newNiifBookValue, accumulatedDepr: newNiifAccumulated }
      },
      temporaryDifference: diffTemporaria,
      deferredTax: isrDiferido,
      journalEntryId,
    });
  } catch (error) {
    console.error('POST depreciate error:', error);
    return NextResponse.json({ error: 'Error al registrar depreciación' }, { status: 500 });
  }
}
