import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { getAuthFromRequest } from '@/lib/auth/jwt';
import { SV_DEPRECIATION_RATES } from '@/lib/sv-chart-of-accounts';

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const auth = await getAuthFromRequest(request);
    if (!auth) return NextResponse.json({ error: 'No autenticado' }, { status: 401 });

    const { id } = await params;
    const asset = await (prisma.fixedAsset as any).findUnique({
      where: { id },
    });
    if (!asset) return NextResponse.json({ error: 'Activo no encontrado' }, { status: 404 });
    if (asset.status !== 'ACTIVE') {
      return NextResponse.json({ error: 'El activo no está activo' }, { status: 400 });
    }
    if (asset.bookValue <= 0) {
      return NextResponse.json({ error: 'El activo ya está completamente depreciado' }, { status: 400 });
    }

    const body = await request.json().catch(() => ({}));
    const now = new Date();
    const year = body.year ?? now.getFullYear();
    const month = body.month ?? (now.getMonth() + 1);

    // Verificar si ya se depreció este mes
    const existing = await (prisma.assetDepreciation as any).findUnique({
      where: { assetId_year_month: { assetId: id, year, month } },
    });
    if (existing) {
      return NextResponse.json(
        { error: `Ya se registró depreciación para ${month}/${year}` },
        { status: 409 }
      );
    }

    // Cuota mensual: (costo - valor residual) / (años * 12)
    const monthlyAmount = (asset.purchaseCost - asset.residualValue) / (asset.usefulLifeYears * 12);
    // No depreciar más allá del valor en libros
    const amount = Math.min(monthlyAmount, asset.bookValue - asset.residualValue);
    const newAccumulated = asset.accumulatedDepr + amount;
    const newBookValue = asset.purchaseCost - newAccumulated;

    const rateConfig = SV_DEPRECIATION_RATES[asset.accountCode];
    const deprCode = rateConfig?.deprCode ?? `${asset.accountCode}D`;

    // Crear asiento contable: DB 6116 / CR {deprCode}
    let journalEntryId: string | null = null;
    try {
      const companyId = asset.companyId;

      const getOrCreate = async (code: string, name: string, type: string) => {
        const existing = await prisma.account.findUnique({
          where: { companyId_code: { companyId, code } },
        });
        if (existing) return existing.id;
        const created = await prisma.account.create({
          data: { companyId, code, name, type },
        });
        return created.id;
      };

      const [debitId, creditId] = await Promise.all([
        getOrCreate('6116', 'Depreciaciones', 'GASTO'),
        getOrCreate(deprCode, `Depreciación Acumulada — ${asset.name}`, 'ACTIVO'),
      ]);

      const entry = await prisma.journalEntry.create({
        data: {
          date: new Date(year, month - 1, 1),
          description: `Depreciación: ${asset.name} (${month}/${year})`,
          companyId,
          metadata: { assetId: id, year, month, autoGenerated: true },
          lines: {
            create: [
              { accountId: debitId, debit: amount, credit: 0 },
              { accountId: creditId, debit: 0, credit: amount },
            ],
          },
        },
      });
      journalEntryId = entry.id;
    } catch (je) {
      console.warn('Journal entry warning (depreciation):', je);
    }

    // Registrar depreciación y actualizar activo
    const [depreciation] = await Promise.all([
      (prisma.assetDepreciation as any).create({
        data: {
          assetId: id,
          year,
          month,
          amount,
          accumulatedDepr: newAccumulated,
          journalEntryId,
        },
      }),
      (prisma.fixedAsset as any).update({
        where: { id },
        data: {
          accumulatedDepr: newAccumulated,
          bookValue: newBookValue,
          status: newBookValue <= asset.residualValue ? 'FULLY_DEPRECIATED' : 'ACTIVE',
        },
      }),
    ]);

    return NextResponse.json({
      depreciation,
      asset: { bookValue: newBookValue, accumulatedDepr: newAccumulated },
      journalEntryId,
    });
  } catch (error) {
    console.error('POST depreciate error:', error);
    return NextResponse.json({ error: 'Error al registrar depreciación' }, { status: 500 });
  }
}
