import { prisma } from '@/lib/prisma';
import { SV_CHART_OF_ACCOUNTS, DEFAULT_ACCOUNT_MAPPING } from '@/lib/sv-chart-of-accounts';

interface TxInput {
  id: string;
  amount: number;
  description: string;
  date: Date;
  companyId: string;
  type: 'INGRESO' | 'EGRESO';
}

interface CategoryInput {
  name: string;
  debitAccountCode?: string | null;
  creditAccountCode?: string | null;
}

// Obtiene o crea una cuenta contable por código
async function getOrCreateAccount(companyId: string, code: string): Promise<string> {
  const existing = await prisma.account.findUnique({
    where: { companyId_code: { companyId, code } },
    select: { id: true },
  });
  if (existing) return existing.id;

  // Auto-crear desde el catálogo SV
  const catalogEntry = SV_CHART_OF_ACCOUNTS.find(a => a.code === code);
  const name = catalogEntry?.name ?? `Cuenta ${code}`;
  const type = catalogEntry?.type ?? 'GASTO';

  const created = await prisma.account.create({
    data: { companyId, code, name, type },
    select: { id: true },
  });
  return created.id;
}

// Determina el mapeo de cuentas: primero usa el de la categoría, luego el default
function resolveAccountCodes(
  tx: TxInput,
  category: CategoryInput
): { debitCode: string; creditCode: string } {
  if (category.debitAccountCode && category.creditAccountCode) {
    return {
      debitCode: category.debitAccountCode,
      creditCode: category.creditAccountCode,
    };
  }

  // Fallback: mapeo por tipo de transacción
  const key = tx.type === 'INGRESO' ? 'INGRESO_DEFAULT' : 'EGRESO_DEFAULT';
  const mapping = DEFAULT_ACCOUNT_MAPPING[key];
  return { debitCode: mapping.debit, creditCode: mapping.credit };
}

// Hook principal: crea el asiento contable automático al crear una transacción
export async function createAutoJournalEntry(
  tx: TxInput,
  category: CategoryInput
): Promise<{ journalEntryId: string } | null> {
  try {
    const { debitCode, creditCode } = resolveAccountCodes(tx, category);

    const [debitAccountId, creditAccountId] = await Promise.all([
      getOrCreateAccount(tx.companyId, debitCode),
      getOrCreateAccount(tx.companyId, creditCode),
    ]);

    const journalEntry = await prisma.journalEntry.create({
      data: {
        date: tx.date,
        description: `Auto: ${tx.description}`,
        reference: tx.id,
        companyId: tx.companyId,
        metadata: {
          transactionId: tx.id,
          type: tx.type,
          debitCode,
          creditCode,
          autoGenerated: true,
        },
        lines: {
          create: [
            {
              accountId: debitAccountId,
              debit: tx.amount,
              credit: 0,
            },
            {
              accountId: creditAccountId,
              debit: 0,
              credit: tx.amount,
            },
          ],
        },
      },
      select: { id: true },
    });

    return { journalEntryId: journalEntry.id };
  } catch (error) {
    console.warn('⚠️ auto-journal warning:', error instanceof Error ? error.message : error);
    return null;
  }
}
